# Generated by Django 5.1.7 on 2025-04-06 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_installation', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Device',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Incident',
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Location',
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('co2_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.device')),
            ],
            options={
                'verbose_name_plural': 'EnvironmentalParameters',
                'db_table': 'environmental_parameters',
            },
        ),
        migrations.CreateModel(
            name='AnalyzedInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_hazard', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('analyzed_at', models.DateTimeField()),
                ('recorded_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.environmentalparameters')),
            ],
            options={
                'verbose_name_plural': 'AnalyzedInformation',
                'db_table': 'analyzed_information',
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('alarm_level', models.CharField(max_length=20)),
                ('alarm_at', models.DateTimeField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.analyzedinformation')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.incident')),
            ],
            options={
                'verbose_name_plural': 'Alarm',
                'db_table': 'alarm',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.location'),
        ),
    ]
