# Generated by Django 5.1.7 on 2025-04-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyzedinformation',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'Анализ данных', 'verbose_name_plural': 'Анализированная информация'},
        ),
        migrations.AlterField(
            model_name='analyzedinformation',
            name='analyzed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время анализа'),
        ),
        migrations.AlterField(
            model_name='analyzedinformation',
            name='fire_hazard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уровень пожарной опасности'),
        ),
        migrations.AlterField(
            model_name='analyzedinformation',
            name='recorded_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.environmentalparameters', verbose_name='Исходные данные'),
        ),
    ]
