# Generated by Django 5.1.7 on 2025-04-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_analyzedinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['-alarm_at'], 'verbose_name': 'Тревога', 'verbose_name_plural': 'Тревоги'},
        ),
        migrations.AlterModelOptions(
            name='analyzedinformation',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'Анализ данных', 'verbose_name_plural': 'Analyzed information'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Инцидент', 'verbose_name_plural': 'Инциденты'},
        ),
        migrations.AlterField(
            model_name='alarm',
            name='alarm_at',
            field=models.DateTimeField(verbose_name='Время активации'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='alarm_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=20, verbose_name='Уровень тревоги'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='monitoring.analyzedinformation', verbose_name='Анализ данных'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='monitoring.incident', verbose_name='Связанный инцидент'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('acknowledged', 'Подтверждена'), ('resolved', 'Решена')], default='active', max_length=20, verbose_name='Статус тревоги'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='detected_at',
            field=models.DateTimeField(verbose_name='Время обнаружения'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время решения'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('investigation', 'Расследование'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='alarm',
            index=models.Index(fields=['status', 'alarm_at'], name='alarm_status_76a002_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'detected_at'], name='incident_status_2c1e59_idx'),
        ),
    ]
