# Generated by Django 5.1.7 on 2025-04-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_alarm_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['-alarm_at'], 'verbose_name': 'Тревога', 'verbose_name_plural': 'Alarm'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-detected_at'], 'verbose_name': 'Инцидент', 'verbose_name_plural': 'Incident'},
        ),
        migrations.AlterField(
            model_name='alarm',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='monitoring.analyzedinformation', verbose_name='Alarm'),
        ),
    ]
