# Generated by Django 5.1.7 on 2025-04-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_alter_alarm_options_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='incident',
            name='time_window_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец временного окна'),
        ),
        migrations.AddField(
            model_name='incident',
            name='time_window_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало временного окна'),
        ),
    ]
