# Generated by Django 5.1.7 on 2025-04-13 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_incident_time_window_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='monitoring.analyzedinformation', verbose_name='Анализ данных'),
        ),
    ]
