# Generated by Django 5.1.7 on 2025-04-15 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_alter_alarm_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('open', 'Открыт'), ('investigation', 'Расследование'), ('resolved', 'Решен'), ('closed', 'Закрыт')], max_length=20, null=True, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('open', 'Открыт'), ('investigation', 'Расследование'), ('resolved', 'Решен'), ('closed', 'Закрыт')], max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'История статуса инцидента',
                'verbose_name_plural': 'Истории статусов инцидентов',
                'db_table': 'incident_status_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='incident_status_2c1e59_idx',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='description',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='detected_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='time_window_end',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='time_window_start',
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('investigation', 'Расследование'), ('resolved', 'Решен'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Текущий статус'),
        ),
        migrations.AlterModelTable(
            name='incident',
            table=None,
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='incidentstatushistory',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='monitoring.incident', verbose_name='Инцидент'),
        ),
    ]
