# Generated by Django 5.1.7 on 2025-04-15 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_incidentstatushistory_alter_incident_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.location', verbose_name='Локация'),
        ),
    ]
