# Generated by Django 5.1.7 on 2025-05-04 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_remove_environmentalparameters_wind_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='incident',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время обнаружения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='incident',
            name='time_window_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец окна'),
        ),
        migrations.AddField(
            model_name='incident',
            name='time_window_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало окна'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('investigation', 'Расследование'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Текущий статус'),
        ),
    ]
