# Generated by Django 5.1.7 on 2025-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_incident_description_incident_detected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalparameters',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
