# Generated by Django 5.2 on 2025-05-16 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_alter_alarm_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='environmentalparameters',
            name='environment_recorde_3f221b_idx',
        ),
        migrations.RenameIndex(
            model_name='environmentalparameters',
            new_name='env_dev_rec_idx',
            old_name='environment_device__354516_idx',
        ),
        migrations.AlterField(
            model_name='alarm',
            name='alarm_at',
            field=models.DateTimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='alarm_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='monitoring.analyzedinformation', verbose_name='Анализ'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarms', to='monitoring.incident', verbose_name='Инцидент'),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('acknowledged', 'Подтверждена'), ('resolved', 'Решена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='environmentalparameters',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Обнаружен'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='monitoring.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыт'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('investigation', 'Расследование'), ('resolved', 'Решён'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time_window_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='time_window_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время смены'),
        ),
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменён'),
        ),
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='new_status',
            field=models.CharField(choices=[('open', 'Открыт'), ('investigation', 'Расследование'), ('resolved', 'Решён'), ('closed', 'Закрыт')], max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='incidentstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('open', 'Открыт'), ('investigation', 'Расследование'), ('resolved', 'Решён'), ('closed', 'Закрыт')], max_length=20, null=True, verbose_name='Старый статус'),
        ),
        migrations.AddIndex(
            model_name='environmentalparameters',
            index=models.Index(condition=models.Q(('processed', False)), fields=['recorded_at'], name='env_processed_false_idx'),
        ),
    ]
